import test from 'node:test';
import assert from 'node:assert/strict';
import {buildNutriContext,buildPersonalContext,detectAssistantIntent} from '../dist/assistantContext.js';

const raw={today:'2026-09-06',student:{full_name:'Ana',primary_goal:'Hipertrofia',training_level:'intermediate'},profile:{objective:'Hipertrofia',protein_goal_g:140,water_goal_ml:2500,allergies:'amendoim'},goals:[{goal_type:'proteína',value:140}],meals:[{meal_date:'2026-09-06',meal_type:'Almoço',calories:500,protein_g:30,carbs_g:60,fat_g:12},{meal_date:'2026-09-05',meal_type:'Jantar',calories:600,protein_g:40}],hydration:[{hydration_date:'2026-09-06',amount_ml:800}],workoutHistory:[{name:'A',completed_at:'2026-09-05'}],logs:[{exercise_name:'Supino',weight:20}],assessments:[{weight:70}],memories:[{memory_key:'preferência',memory_value:'rápido'}],plan:{title:'Plano'},workouts:[{name:'Peito'}]};
test('identifica intenções distintas',()=>{assert.equal(detectAssistantIntent('Como está minha hidratação hoje?','nutrition'),'HYDRATION');assert.equal(detectAssistantIntent('Como estou evoluindo no treino?','personal'),'TRAINING_PROGRESS');assert.equal(detectAssistantIntent('Esta foto tem arroz?','nutrition',true),'MEAL_ANALYSIS');assert.equal(detectAssistantIntent('Estou com dor aguda','personal'),'SAFETY')});
test('Nutri recomenda com dados do dia e sem despejar treino',()=>{const c=buildNutriContext(raw,'RECOMMENDATION','O que posso comer agora?',[]);assert.equal(c.nutrition.totals_today.protein_g,30);assert.equal(c.profile.allergies,'amendoim');assert.equal(c.training_snapshot,undefined);assert.equal(c.nutrition.plan.title,'Plano')});
test('Nutri progresso recebe histórico relevante',()=>{const c=buildNutriContext(raw,'PROGRESS','Como estou?',[]);assert.ok(c.training_snapshot);assert.equal(c.nutrition.checkin,null)});
test('Personal evolução recebe treino e logs',()=>{const c=buildPersonalContext(raw,'TRAINING_PROGRESS','Como estou evoluindo?',[]);assert.equal(c.training.logs[0].weight,20);assert.equal(c.training.active_workouts[0].name,'Peito');assert.equal(c.nutrition_snapshot,undefined)});
test('continuidade preserva turnos recentes com limite',()=>{const turns=Array.from({length:20},(_,i)=>({role:i%2?'assistant':'user',content:`turno ${i}`}));const c=buildPersonalContext(raw,'QUESTION','E amanhã?',turns);assert.equal(c.conversation.length,10);assert.equal(c.conversation.at(-1).content,'turno 19')});
