services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: multigym
      POSTGRES_USER: multigym
      POSTGRES_PASSWORD: multigym
    ports:
      - "5432:5432"
    volumes:
      - multigym_pgdata:/var/lib/postgresql/data
volumes:
  multigym_pgdata:
