type NutritionContext={
  profile:any;
  meals:any[];
  goals:any[];
  checkin:any;
  workouts:any[];
  plan:any;
};

const MODEL=process.env.GROQ_MODEL||'openai/gpt-oss-120b';
const timeoutMs=Number(process.env.GROQ_TIMEOUT_MS||12000);
const unsafeOutput=/\b(diagnos(ticar|tico)|prescri(ba|ver)|medica(mento|ção)|insulina|suspenda|pare de tomar|dose exata|jejum extremo|vomit|laxante)\b/i;
const safetyMessage='Posso ajudar com a organização da sua alimentação, mas esse pedido precisa de orientação profissional. Posso ajudar a registrar o que aconteceu e organizar suas dúvidas.';

export async function askGroqNutrition(message:string,context:NutritionContext,imageDataUrl?:string):Promise<string|null>{
  const key=process.env.GROQ_API_KEY;
  if(!key)return null;
  const model=imageDataUrl?(process.env.GROQ_VISION_MODEL||'meta-llama/llama-4-scout-17b-16e-instruct'):MODEL;
  const controller=new AbortController();
  const timer=setTimeout(()=>controller.abort(),timeoutMs);
  const planningRequest=/plano|ação|objetivo|emagrec|perder|ganhar|massa|recompos|estratégia|estrategia|meta/i.test(message);
  const system=`Você é o assistente NutriGym, uma experiência premium de acompanhamento nutricional integrada ao treino. Responda em português brasileiro, com profundidade proporcional ao pedido, tom humano, seguro, claro e profissional, sem parecer um chatbot genérico. Antes de responder, analise silenciosamente o contexto autorizado recebido. Use somente esse contexto e não invente dados. Não explique seu processo interno nem fale sobre o modelo de IA. Não use linguagem de culpa. Respeite alergias e restrições antes de sugerir qualquer opção. Não altere silenciosamente um plano profissional. Não repita avisos genéricos em toda resposta: só mencione a necessidade de um profissional quando o pedido envolver diagnóstico, tratamento, medicamento, risco clínico ou mudança de plano. Quando o aluno pedir um plano de ação, converse como um bom coach nutricional: confirme a meta, interprete os dados disponíveis, indique um ritmo realista sem prometer resultado e entregue ações concretas para começar: comece confirmando a meta, indique um ritmo realista sem prometer resultado, use composição corporal, medidas, hidratação e histórico de treino quando existirem, organize alimentação, treino, movimento e acompanhamento semanal, e termine com os poucos dados que ainda faltarem. Use composição corporal, medidas, hidratação e histórico de treino quando existirem. Prefira texto corrido e listas legíveis no celular; não use tabelas Markdown, asteriscos de formatação ou despeje todos os campos do perfil. Se um dado não existir no contexto, não invente: siga com uma orientação provisória e termine com no máximo três perguntas objetivas. Diferencie claramente o que veio dos registros do aluno do que é uma sugestão geral. Não diga para usar outro aplicativo. Quando fizer sentido, organize em 🎯 Meta; 1. Alimentação; 2. Treino; 3. Cardio e movimento; 4. Acompanhamento semanal; 5. Nossa estratégia em fases. ${planningRequest?'Para este pedido, seja completo e prático, com títulos curtos, emojis discretos, exemplos de ações e uma rotina inicial. Não pare no meio nem responda como um formulário.':''} ${imageDataUrl?'Analise a imagem apenas de forma visual e aproximada. Liste os alimentos possivelmente identificados e forneça uma faixa de calorias, nunca um número exato. Diga que a pessoa deve confirmar ou corrigir os itens. Não trate a imagem como medição nutricional.':''} Contexto autorizado: ${JSON.stringify(context)}`;
  try{
    const userContent:any=imageDataUrl?[{type:'text',text:message.slice(0,500)},{type:'image_url',image_url:{url:imageDataUrl}}]:message.slice(0,500);
    const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Authorization':`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:0.2,max_tokens:700,messages:[{role:'system',content:system},{role:'user',content:userContent}]}),signal:controller.signal});
    if(!response.ok)return null;
    const data:any=await response.json();
    const text=String(data?.choices?.[0]?.message?.content||'').trim();
    if(!text||text.length>3000||unsafeOutput.test(text))return safetyMessage;
    return text;
  }catch{return null}finally{clearTimeout(timer)}
}

export async function estimateMealNutrition(description:string,mealType:string):Promise<{calories:number;protein_g:number;carbs_g:number;fat_g:number;estimated:boolean}> {
  const fallback=()=>{const text=`${mealType} ${description}`.toLowerCase();let calories=350,protein=18,carbs=42,fat=12;if(/arroz|macarrão|massa|batata|pão|aveia/.test(text)){calories+=120;carbs+=24}if(/feijão|lentilha|grão/.test(text)){calories+=80;protein+=5;carbs+=14}if(/frango|peito|carne|patinho|peixe|atum|ovo|ovos/.test(text)){calories+=150;protein+=20;fat+=5}if(/salada|legume|verdura|fruta|banana|maçã|maca/.test(text)){calories+=60;carbs+=12}if(/frit|pizza|hambúrguer|hamburguer|doce|chocolate/.test(text)){calories+=220;fat+=12;carbs+=20}return {calories:Math.round(calories),protein_g:Math.round(protein),carbs_g:Math.round(carbs),fat_g:Math.round(fat),estimated:true}};
  const key=process.env.GROQ_API_KEY;if(!key)return fallback();const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),Number(process.env.GROQ_TIMEOUT_MS||12000));try{const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Authorization':`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,temperature:0,max_tokens:180,messages:[{role:'system',content:'Você estima nutrientes de refeições descritas em português brasileiro. Considere porções médias quando a pessoa não informar quantidade. Responda somente JSON válido, sem markdown, com os campos calories, protein_g, carbs_g e fat_g, todos números não negativos. São estimativas aproximadas, não uma avaliação clínica.'},{role:'user',content:`Tipo: ${mealType}. Refeição: ${description.slice(0,500)}`}]}),signal:controller.signal});if(!response.ok)return fallback();const data:any=await response.json(),raw=String(data?.choices?.[0]?.message?.content||'').replace(/```json|```/g,'').trim(),parsed=JSON.parse(raw);const values={calories:Math.round(Number(parsed.calories)),protein_g:Math.round(Number(parsed.protein_g)),carbs_g:Math.round(Number(parsed.carbs_g)),fat_g:Math.round(Number(parsed.fat_g)),estimated:true};if(!Number.isFinite(values.calories)||!Number.isFinite(values.protein_g)||!Number.isFinite(values.carbs_g)||!Number.isFinite(values.fat_g)||values.calories>20000||values.protein_g>1000||values.carbs_g>1500||values.fat_g>500)return fallback();return values}catch{return fallback()}finally{clearTimeout(timer)}}

type PersonalGymContext={student:any;profile:any;workouts:any[];workoutHistory:any[];logs:any[];assessments:any[]};

export async function askGroqPersonal(message:string,context:PersonalGymContext):Promise<string|null>{
  const key=process.env.GROQ_API_KEY;if(!key)return null;
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeoutMs);
  const system=`Você é o assistente Personal Gym, um personal trainer virtual integrado ao MultiGym. Responda em português brasileiro, com tom humano, profissional, claro e prático. Analise silenciosamente o contexto autorizado do aluno antes de responder. Use somente os dados disponíveis e não invente treino, carga, repetições ou limitações. Ajude a entender o treino do dia, organizar a sessão, melhorar a técnica, controlar ritmo, descanso, aquecimento, progressão e recuperação. Quando o aluno pedir o treino do dia, apresente apenas o treino ativo que estiver no contexto, organizado por exercício, séries, repetições, carga, descanso e instrução. Quando pedir ajuda de execução, explique em passos: preparação, movimento, respiração, erros comuns e sinal para parar. Nunca diagnostique lesões, prescreva tratamento, altere medicamentos, incentive treino com dor aguda ou prometa resultados. Se houver dor forte, falta de ar, tontura, perda de força ou lesão, oriente interromper e buscar avaliação profissional. Não substitua um profissional de educação física. Não use tabelas Markdown nem asteriscos visíveis; use títulos curtos e listas legíveis no celular. Contexto autorizado: ${JSON.stringify(context)}`;
  try{const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Authorization':`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,temperature:0.2,max_tokens:800,messages:[{role:'system',content:system},{role:'user',content:message.slice(0,700)}]}),signal:controller.signal});if(!response.ok)return null;const data:any=await response.json();const text=String(data?.choices?.[0]?.message?.content||'').trim();if(!text||text.length>3500||unsafeOutput.test(text))return 'Posso ajudar com a organização do treino e a execução dos exercícios, mas esse pedido precisa de avaliação profissional. Se quiser, descreva o exercício ou a dificuldade técnica.';return text}catch{return null}finally{clearTimeout(timer)}
}
