import { z } from 'zod';
import { createHash } from 'node:crypto';
import { pool, withTenant } from './db.js';
const tokenHash=(v:string)=>createHash('sha256').update(v).digest('hex');
export async function registerModules(app:any){
  app.addHook('preHandler',async(req:any,reply:any)=>{if(!req.url.startsWith('/api/'))return;const raw=req.headers.authorization?.replace('Bearer ','');if(!raw)return reply.code(401).send({error:'Faça login para continuar.'});const r=await pool.query('SELECT u.id,u.name,u.email,u.role,u.gym_id,g.name gym_name FROM sessions s JOIN users u ON u.id=s.user_id JOIN gyms g ON g.id=s.gym_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now() AND u.status=\'active\'', [tokenHash(raw)]);if(!r.rowCount)return reply.code(401).send({error:'Sessão expirada.'});req.user=r.rows[0]});
  app.get('/api/dashboard',async(req:any)=>withTenant(req.user.gym_id,async(c)=>{const [s,e,p,a]=await Promise.all([c.query("SELECT count(*)::int total FROM students WHERE status='active'"),c.query("SELECT count(*)::int total FROM enrollments WHERE status IN ('expiring','expired')"),c.query("SELECT coalesce(sum(amount),0)::numeric total FROM payments WHERE status='paid' AND paid_at>=date_trunc('month',now())"),c.query("SELECT count(*)::int total FROM appointments WHERE starts_at::date=current_date")]);return {gym:req.user.gym_name,students:s.rows[0].total,enrollments_attention:e.rows[0].total,revenue:Number(p.rows[0].total),appointments:a.rows[0].total}}));
  app.get('/api/students',async(req:any)=>{const q=String(req.query?.q||'');return withTenant(req.user.gym_id,c=>c.query('SELECT id,full_name,cpf,phone,email,status FROM students WHERE ($1=\'\' OR full_name ILIKE $2 OR cpf ILIKE $2 OR phone ILIKE $2) ORDER BY full_name LIMIT 100',[q,`%${q}%`]).then(x=>x.rows))});
  app.post('/api/students',async(req:any,reply:any)=>{const d=z.object({full_name:z.string().min(2),cpf:z.string().optional(),birth_date:z.string().optional(),phone:z.string().optional(),email:z.string().email().optional(),notes:z.string().optional()}).parse(req.body);const r=await withTenant(req.user.gym_id,c=>c.query('INSERT INTO students (gym_id,full_name,cpf,birth_date,phone,email,notes) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING *',[req.user.gym_id,d.full_name,d.cpf||null,d.birth_date||null,d.phone||null,d.email||null,d.notes||null]));return reply.code(201).send(r.rows[0])});
  app.get('/api/plans',async(req:any)=>withTenant(req.user.gym_id,c=>c.query('SELECT * FROM plans WHERE status=\'active\' ORDER BY price').then(x=>x.rows)));
  app.post('/api/plans',async(req:any,reply:any)=>{const d=z.object({name:z.string().min(2),price:z.coerce.number().nonnegative(),duration_days:z.coerce.number().int().positive()}).parse(req.body);const r=await withTenant(req.user.gym_id,c=>c.query('INSERT INTO plans(gym_id,name,price,duration_days) VALUES($1,$2,$3,$4) RETURNING *',[req.user.gym_id,d.name,d.price,d.duration_days]));return reply.code(201).send(r.rows[0])});
  app.get('/api/enrollments',async(req:any)=>withTenant(req.user.gym_id,c=>c.query('SELECT e.*,s.full_name student_name,p.name plan_name FROM enrollments e JOIN students s ON s.id=e.student_id JOIN plans p ON p.id=e.plan_id ORDER BY e.ends_on DESC LIMIT 100').then(x=>x.rows)));
  app.post('/api/enrollments',async(req:any,reply:any)=>{const d=z.object({student_id:z.string().uuid(),plan_id:z.string().uuid(),starts_on:z.string(),ends_on:z.string(),amount:z.coerce.number().nonnegative(),method:z.enum(['cash','pix','card','transfer','other']).optional()}).parse(req.body);const r=await withTenant(req.user.gym_id,c=>c.query('INSERT INTO enrollments(gym_id,student_id,plan_id,starts_on,ends_on,amount,method,created_by) SELECT $1,s.id,p.id,$3,$4,$5,$6,$7 FROM students s,plans p WHERE s.id=$2 AND p.id=$8 AND s.gym_id=$1 AND p.gym_id=$1 RETURNING *',[req.user.gym_id,d.student_id,d.starts_on,d.ends_on,d.amount,d.method||null,req.user.id,d.plan_id]));if(!r.rowCount)return reply.code(400).send({error:'Aluno ou plano não encontrado.'});return reply.code(201).send(r.rows[0])});
  app.get('/api/payments',async(req:any)=>withTenant(req.user.gym_id,c=>c.query('SELECT p.*,s.full_name student_name FROM payments p JOIN students s ON s.id=p.student_id ORDER BY p.created_at DESC LIMIT 100').then(x=>x.rows)));
  app.post('/api/payments',async(req:any,reply:any)=>{const d=z.object({student_id:z.string().uuid(),enrollment_id:z.string().uuid().optional(),amount:z.coerce.number().positive(),method:z.enum(['cash','pix','card','transfer','other']),notes:z.string().optional()}).parse(req.body);const r=await withTenant(req.user.gym_id,c=>c.query('INSERT INTO payments(gym_id,student_id,enrollment_id,amount,paid_at,method,notes,created_by) SELECT $1,s.id,$3,$4,now(),$5,$6,$7 FROM students s WHERE s.id=$2 AND s.gym_id=$1 RETURNING *',[req.user.gym_id,d.student_id,d.enrollment_id||null,d.amount,d.method,d.notes||null,req.user.id]));if(!r.rowCount)return reply.code(400).send({error:'Aluno não encontrado.'});return reply.code(201).send(r.rows[0])});
  app.get('/api/appointments',async(req:any)=>withTenant(req.user.gym_id,c=>c.query('SELECT a.*,s.full_name student_name,u.name professional_name FROM appointments a LEFT JOIN students s ON s.id=a.student_id LEFT JOIN users u ON u.id=a.professional_id WHERE a.starts_at>=now()-interval \'1 day\' ORDER BY a.starts_at LIMIT 100').then(x=>x.rows)));
  app.post('/api/appointments',async(req:any,reply:any)=>{const d=z.object({title:z.string().min(2),type:z.enum(['assessment','personal','class','meeting','other']),starts_at:z.string(),ends_at:z.string(),student_id:z.string().uuid().optional(),notes:z.string().optional()}).parse(req.body);const r=await withTenant(req.user.gym_id,c=>c.query('INSERT INTO appointments(gym_id,title,type,starts_at,ends_at,student_id,professional_id,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[req.user.gym_id,d.title,d.type,d.starts_at,d.ends_at,d.student_id||null,req.user.id,d.notes||null]));return reply.code(201).send(r.rows[0])});
}
