type VisionContext={profile:any;meals:any[];goals:any[];checkin:any;workouts:any[];plan:any};
const model=process.env.OPENAI_VISION_MODEL||'gpt-4o-mini';
const unsafe=/\b(diagnos(ticar|tico)|prescri(ba|ver)|medica(mento|ção)|insulina|suspenda|pare de tomar|dose exata|jejum extremo|vomit|laxante)\b/i;
const safe='Posso ajudar a registrar e organizar sua refeição, mas não faço diagnóstico nem prescrevo tratamento. Para orientação clínica, procure seu nutricionista ou médico.';
export async function askOpenAIVision(message:string,context:VisionContext,imageDataUrl:string):Promise<string|null>{
  const key=process.env.OPENAI_API_KEY;if(!key)return null;
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
  const system=`Você é o analisador visual do NutriGym. Responda em português brasileiro. Analise a foto de modo aproximado, sem afirmar certeza. Liste os alimentos possivelmente identificados, peça confirmação/correção e, somente se for razoável, dê uma faixa ampla de calorias. Nunca dê um número exato, nunca diagnostique, prescreva, recomende medicamento ou dieta extrema. Respeite alergias e restrições do contexto. A imagem não é uma medição nutricional. Contexto autorizado: ${JSON.stringify(context)}`;
  try{const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:0.1,max_tokens:450,messages:[{role:'system',content:system},{role:'user',content:[{type:'text',text:message.slice(0,500)},{type:'image_url',image_url:{url:imageDataUrl}}]}]}),signal:controller.signal});if(!r.ok)return null;const data:any=await r.json(),text=String(data?.choices?.[0]?.message?.content||'').trim();if(!text||text.length>3000)return null;if(unsafe.test(text))return safe;return text}catch{return null}finally{clearTimeout(timer)}}
