import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {api,post,put,del} from './api';
import {Activity,ArrowUpRight,CalendarDays,CheckCircle2,CircleDollarSign,ClipboardList,Clock, Dumbbell,FileBarChart,LayoutDashboard,LogOut,Menu,Plus,Search,Settings,Users,WalletCards,X,ChevronRight,AlertTriangle} from 'lucide-react';
import './styles.css';

type User={id:string,name:string,email:string,role:string,gymId:string,gymName:string};
type Page='dashboard'|'students'|'enrollments'|'workouts'|'finance'|'agenda'|'reports'|'settings';

const money=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const date=(v:any)=>v?new Date(v+'T00:00:00').toLocaleDateString('pt-BR'):'—';
const dateTime=(v:any)=>v?new Date(v).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'—';

function App(){
 const [user,setUser]=useState<User|null>(()=>{try{return JSON.parse(localStorage.getItem('multigym_user')||'null')}catch{return null}});
 const [page,setPage]=useState<Page>((location.hash.replace('#','') as Page)||'dashboard');
 useEffect(()=>{const fn=()=>{const p=location.hash.replace('#','') as Page;if(['dashboard','students','enrollments','workouts','finance','agenda','reports','settings'].includes(p))setPage(p)};window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 const [mobile,setMobile]=useState(false);
 const login=(u:User,t:string)=>{localStorage.setItem('multigym_token',t);localStorage.setItem('multigym_user',JSON.stringify(u));setUser(u)};
 const logout=async()=>{try{await api('/auth/logout',{method:'POST'})}catch{}localStorage.clear();setUser(null)};
 if(!user)return <Auth onLogin={login}/>;
 const nav:[Page,string,React.ReactNode][]=[['dashboard','Dashboard',<LayoutDashboard size={18}/>],['students','Alunos',<Users size={18}/>],['enrollments','Matrículas',<ClipboardList size={18}/>],['workouts','Treinos',<Dumbbell size={18}/>],['finance','Financeiro',<WalletCards size={18}/>],['agenda','Agenda',<CalendarDays size={18}/>],['reports','Relatórios',<FileBarChart size={18}/>],['settings','Configurações',<Settings size={18}/>]];
 return <div className="shell">
  <aside className={'sidebar '+(mobile?'open':'')}>
   <div className="brand"><div className="mg">MG</div><div><strong>MultiGym</strong><small>Sistema para academias</small></div><button className="closeMobile" onClick={()=>setMobile(false)}><X size={18}/></button></div>
   <nav>{nav.map(([id,label,icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);location.hash=id;setMobile(false)}}>{icon}<span>{label}</span></button>)}</nav>
   <div className="sidebarBottom"><div className="planBox"><span>PLANO ATUAL</span><b>Básico</b><small>Gestão essencial</small></div><div className="profile"><div className="avatar">{user.name.slice(0,1).toUpperCase()}</div><div><b>{user.name}</b><small>{user.role==='admin'?'Administrador':user.role==='instructor'?'Instrutor':'Recepção'}</small></div></div><button className="logout" onClick={logout}><LogOut size={17}/>Sair</button></div>
  </aside>
  {mobile&&<div className="overlay" onClick={()=>setMobile(false)}/>}
  <main className="main">
   <header className="topbar"><button className="mobileMenu" onClick={()=>setMobile(true)}><Menu/></button><div><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><span>{user.gymName}</span></div><div className="topActions"><div className="notification"><AlertTriangle size={19}/><i>!</i></div><div className="userMini"><div className="avatar small">{user.name.slice(0,1).toUpperCase()}</div><span>{user.name}</span></div></div></header>
   <div className="page"><PageContent page={page} user={user}/></div>
  </main>
 </div>
}

function Auth({onLogin}:{onLogin:(u:User,t:string)=>void}){
 const [mode,setMode]=useState<'login'|'signup'>('login'); const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{
  const data=mode==='login'?await post('/auth/login',{email:f.get('email'),password:f.get('password')}):await post('/auth/signup',{gymName:f.get('gymName'),name:f.get('name'),email:f.get('email'),password:f.get('password')});
  if(mode==='signup'){const l=await post('/auth/login',{email:f.get('email'),password:f.get('password')});onLogin(l.user,l.token)}else onLogin(data.user,data.token);
 }catch(err:any){setError(err.message)}finally{setBusy(false)}};
 return <div className="auth"><div className="authCard"><div className="authBrand"><div className="mg">MG</div><div><strong>MultiGym</strong><small>Sistema para academias</small></div></div><div className="authIntro"><span>GESTÃO SIMPLES</span><h1>{mode==='login'?'Sua academia, sob controle.':'Comece sua gestão.'}</h1><p>{mode==='login'?'Acesse o painel da sua academia e cuide do essencial em poucos cliques.':'Crie sua academia e tenha um ambiente completo para alunos, matrículas e treinos.'}</p></div>
 <form onSubmit={submit}>{mode==='signup'&&<><label>Nome da academia<input name="gymName" required placeholder="Academia Força Total"/></label><label>Seu nome<input name="name" required placeholder="Nome completo"/></label></>}<label>E-mail<input type="email" name="email" required placeholder="voce@academia.com"/></label><label>Senha<input type="password" name="password" required minLength={8} placeholder="Mínimo 8 caracteres"/></label>{error&&<div className="error">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Aguarde…':mode==='login'?'Entrar no sistema':'Criar academia'}</button></form>
 <button className="switch" onClick={()=>{setMode(mode==='login'?'signup':'login');setError('')}}>{mode==='login'?'Ainda não tenho uma conta':'Já tenho uma conta'}</button></div><div className="authVisual"><div className="visualCard"><span>MultiGym</span><strong>O essencial da sua academia<br/>em um só lugar.</strong><div className="visualStats"><b>128<small>Alunos ativos</small></b><b>R$ 12,5k<small>Faturamento</small></b></div></div></div></div>
}

function PageContent({page,user}:{page:Page,user:User}){
 if(page==='dashboard')return <Dashboard/>;
 if(page==='students')return <Students/>;
 if(page==='enrollments')return <Enrollments/>;
 if(page==='workouts')return <Workouts/>;
 if(page==='finance')return <Finance/>;
 if(page==='agenda')return <Agenda/>;
 if(page==='reports')return <Reports/>;
 return <SettingsPage user={user}/>;
}

function Dashboard(){
 const [d,setD]=useState<any>(null);const [loading,setLoading]=useState(true);
 const load=()=>api('/api/dashboard').then(setD).finally(()=>setLoading(false));useEffect(load,[]);
 if(loading)return <Loading/>;if(!d)return null;
 return <><div className="welcomeRow"><div><h2>Visão geral</h2><p>Resumo da sua academia hoje.</p></div><button className="primary" onClick={()=>location.hash='students'}><Plus size={17}/>Novo aluno</button></div>
 <div className="kpis"><Kpi icon={<Users/>} title="Alunos ativos" value={d.students} note="base atual" tone="red"/><Kpi icon={<Clock/>} title="Matrículas vencendo" value={d.enrollmentsExpiring} note="próximos 7 dias" tone="amber"/><Kpi icon={<AlertTriangle/>} title="Matrículas vencidas" value={d.enrollmentsExpired} note="atenção necessária" tone="danger"/><Kpi icon={<CircleDollarSign/>} title="Faturamento do mês" value={money(d.revenue)} note={`${d.revenueGrowth>=0?'+':''}${d.revenueGrowth.toFixed(1)}% vs. mês anterior`} tone="green"/></div>
 <div className="dashboardGrid"><section className="card wide"><div className="sectionHead"><div><h3>Resumo financeiro</h3><span>Faturamento do mês</span></div><ArrowUpRight size={19}/></div><div className="financeNumbers"><div><small>Receitas</small><b>{money(d.revenue)}</b></div><div><small>Recebidos</small><b>{money(d.revenue)}</b></div><div><small>Pendentes</small><b className="dangerText">{money(d.pending)}</b></div></div><div className="fakeChart">{[22,31,27,45,40,55,50,68,61,76,72,88].map((v,i)=><i key={i} style={{height:`${v}%`}}/>)}</div><div className="chartLabels"><span>Início do mês</span><span>Hoje</span></div></section>
 <section className="card attendance"><div className="sectionHead"><div><h3>Presença hoje</h3><span>Check-ins registrados</span></div><Activity size={19}/></div><div className="donut"><div><b>{d.checkins}</b><span>presentes</span></div></div><small>de {d.students} alunos ativos</small></section>
 <section className="card quick"><div className="sectionHead"><div><h3>Ações rápidas</h3><span>Atalhos do dia a dia</span></div></div><div className="quickGrid"><Quick label="Novo aluno" icon={<Users/>}/><Quick label="Nova matrícula" icon={<ClipboardList/>}/><Quick label="Novo treino" icon={<Dumbbell/>}/><Quick label="Receber pagamento" icon={<WalletCards/>}/></div></section>
 <section className="card"><div className="sectionHead"><div><h3>Novos alunos</h3><span>Cadastros recentes</span></div></div><div className="list">{d.recentStudents.map((s:any)=><div className="listItem" key={s.id}><div className="avatar">{s.full_name.slice(0,1)}</div><div><b>{s.full_name}</b><small>{s.phone||'Sem telefone'}</small></div><ChevronRight size={16}/></div>)}{!d.recentStudents.length&&<Empty text="Nenhum aluno cadastrado."/>}</div></section>
 <section className="card today"><div className="sectionHead"><div><h3>Hoje</h3><span>Compromissos</span></div><CalendarDays size={19}/></div><div className="bigNumber">{d.appointments}<small>agendamentos</small></div><div className="mutedBox">Use a Agenda para criar avaliações, aulas e treinos.</div></section></div></>
}

function Kpi({icon,title,value,note,tone}:{icon:any,title:string,value:any,note:string,tone:string}){return <div className="card kpi"><div className={'icon '+tone}>{icon}</div><div><span>{title}</span><b>{value}</b><small>{note}</small></div></div>}
function Quick({label,icon}:{label:string,icon:any}){const target=label==='Novo aluno'?'students':label==='Nova matrícula'?'enrollments':label==='Novo treino'?'workouts':'finance';return <button className="quickBtn" onClick={()=>{location.hash=target}}>{icon}<span>{label}</span></button>}

function Students(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[modal,setModal]=useState(false),[detail,setDetail]=useState<any>(null),[loading,setLoading]=useState(true);
 const load=()=>api('/api/students?q='+encodeURIComponent(q)).then(setRows).finally(()=>setLoading(false));useEffect(()=>{const t=setTimeout(load,250);return()=>clearTimeout(t)},[q]);
 const save=async(data:any)=>{await post('/api/students',data);setModal(false);load()}; 
 return <><Toolbar title="Alunos" subtitle={`${rows.length} registros`} button="Novo aluno" onClick={()=>setModal(true)} search={q} setSearch={setQ}/><section className="card tableCard">{loading?<Loading/>:<Table headers={['Aluno','Telefone','Plano','Vencimento','Status','Ações']} rows={rows.map(s=><tr key={s.id}><td><button className="nameBtn" onClick={()=>api('/api/students/'+s.id).then(setDetail)}><div className="avatar">{s.full_name.slice(0,1)}</div><b>{s.full_name}</b></button></td><td>{s.phone||'—'}</td><td>{s.plan_name||'Sem plano'}</td><td>{date(s.ends_on)}</td><td><Badge text={s.enrollment_status==='expired'?'Vencida':s.enrollment_status==='active'?'Ativa':s.enrollment_status==='expiring'?'Vencendo':'Sem matrícula'} tone={s.enrollment_status==='active'?'green':s.enrollment_status==='expired'?'red':'amber'}/></td><td><button className="linkBtn" onClick={()=>api('/api/students/'+s.id).then(setDetail)}>Ver ficha</button></td></tr>)}/>}</section>{modal&&<StudentModal onClose={()=>setModal(false)} onSave={save}/>} {detail&&<StudentDetail data={detail} onClose={()=>setDetail(null)}/>}</>
}

function StudentModal({onClose,onSave}:{onClose:()=>void,onSave:(d:any)=>Promise<void>}){return <Modal title="Novo aluno" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({full_name:f.get('full_name'),cpf:f.get('cpf'),birth_date:f.get('birth_date'),phone:f.get('phone'),email:f.get('email'),gender:f.get('gender'),notes:f.get('notes')})}}><div className="formGrid"><label>Nome completo<input name="full_name" required/></label><label>CPF<input name="cpf"/></label><label>Data de nascimento<input type="date" name="birth_date"/></label><label>Sexo<select name="gender"><option value="">Não informar</option><option>Feminino</option><option>Masculino</option><option>Outro</option></select></label><label>Telefone<input name="phone"/></label><label>E-mail<input type="email" name="email"/></label><label className="fullField">Observações<textarea name="notes"/></label></div><FormActions onClose={onClose}/></form></Modal>}
function StudentDetail({data,onClose}:{data:any,onClose:()=>void}){const s=data.student;const [edit,setEdit]=useState(false);const [busy,setBusy]=useState(false);return <>{!edit?<Modal title={s.full_name} onClose={onClose}><div className="detailHeader"><div className="avatar large">{s.full_name.slice(0,1)}</div><div><b>{s.email||'Sem e-mail'}</b><span>{s.phone||'Sem telefone'} · {s.cpf||'CPF não informado'}</span></div><button className="secondary smallBtn" onClick={()=>setEdit(true)}>Editar</button></div><div className="detailGrid"><Info title="Matrículas" value={String(data.enrollments.length)}/><Info title="Treinos" value={String(data.workouts.length)}/><Info title="Pagamentos" value={String(data.payments.length)}/><Info title="Check-ins" value={String(data.checkins.length)}/></div><button className="primary" onClick={async()=>{setBusy(true);try{await post('/api/students/'+s.id+'/checkin');alert('Check-in registrado.')}finally{setBusy(false)}}} disabled={busy}>{busy?'Registrando…':'Registrar check-in'}</button><h3>Histórico de matrículas</h3><div className="miniList">{data.enrollments.map((e:any)=><div key={e.id}><b>{e.plan_name}</b><span>{date(e.starts_on)} → {date(e.ends_on)}</span><Badge text={e.status} tone={e.status==='active'?'green':'amber'}/></div>)}</div></Modal>:<Modal title="Editar aluno" onClose={()=>setEdit(false)}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await put('/api/students/'+s.id,{full_name:f.get('full_name'),cpf:f.get('cpf'),birth_date:f.get('birth_date'),gender:f.get('gender'),phone:f.get('phone'),email:f.get('email'),notes:f.get('notes')});setEdit(false);alert('Aluno atualizado.')}finally{setBusy(false)}}}><div className="formGrid"><label>Nome completo<input name="full_name" defaultValue={s.full_name} required/></label><label>CPF<input name="cpf" defaultValue={s.cpf||''}/></label><label>Data de nascimento<input type="date" name="birth_date" defaultValue={s.birth_date?String(s.birth_date).slice(0,10):''}/></label><label>Sexo<input name="gender" defaultValue={s.gender||''}/></label><label>Telefone<input name="phone" defaultValue={s.phone||''}/></label><label>E-mail<input type="email" name="email" defaultValue={s.email||''}/></label><label className="fullField">Observações<textarea name="notes" defaultValue={s.notes||''}/></label></div><div className="formActions"><button type="button" className="secondary" onClick={()=>setEdit(false)}>Cancelar</button><button type="submit" className="primary" disabled={busy}>{busy?'Salvando…':'Salvar alterações'}</button></div></form></Modal>}</>}
function Info({title,value}:{title:string,value:string}){return <div className="infoBox"><small>{title}</small><b>{value}</b></div>}

function Enrollments(){
 const [rows,setRows]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[plans,setPlans]=useState<any[]>([]),[modal,setModal]=useState(false);
 const load=()=>Promise.all([api('/api/enrollments'),api('/api/students'),api('/api/plans')]).then(([e,s,p])=>{setRows(e);setStudents(s);setPlans(p)});useEffect(()=>{load()},[]);
 const save=async(d:any)=>{await post('/api/enrollments',d);setModal(false);load()};
 return <><Toolbar title="Matrículas" subtitle="Ciclo de vida dos planos" button="Nova matrícula" onClick={()=>setModal(true)}/><section className="card tableCard"><Table headers={['Aluno','Plano','Período','Valor','Status','Ações']} rows={rows.map(e=><tr key={e.id}><td><b>{e.student_name}</b></td><td>{e.plan_name}</td><td>{date(e.starts_on)} → {date(e.ends_on)}</td><td>{money(e.amount)}</td><td><Badge text={e.display_status||e.status} tone={(e.display_status||e.status)==='active'?'green':(e.display_status||e.status)==='cancelled'?'gray':'amber'}/></td><td><button className="linkBtn" onClick={async()=>{const plan=plans.find(p=>p.id===e.plan_id);if(!plan)return;const start=new Date();const end=new Date(start);end.setDate(end.getDate()+plan.duration_days);await post('/api/enrollments/'+e.id+'/renew',{plan_id:e.plan_id,starts_on:start.toISOString().slice(0,10),ends_on:end.toISOString().slice(0,10),amount:plan.price});load()}}>Renovar</button></td></tr>)}/></section>{modal&&<EnrollmentModal students={students} plans={plans} onClose={()=>setModal(false)} onSave={save}/>}</>
}
function EnrollmentModal({students,plans,onClose,onSave}:{students:any[],plans:any[],onClose:()=>void,onSave:(d:any)=>Promise<void>}){const [plan,setPlan]=useState<any>(plans[0]);const [start,setStart]=useState(new Date().toISOString().slice(0,10));const end=useMemo(()=>{const d=new Date(start+'T00:00:00');d.setDate(d.getDate()+(plan?.duration_days||30)-1);return d.toISOString().slice(0,10)},[start,plan]);return <Modal title="Nova matrícula" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({student_id:f.get('student_id'),plan_id:plan.id,starts_on:start,ends_on:end,amount:plan.price,method:f.get('method')})}}><label>Aluno<select name="student_id" required><option value="">Selecione</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>Plano<select value={plan?.id||''} onChange={e=>setPlan(plans.find(p=>p.id===e.target.value))}>{plans.map(p=><option key={p.id} value={p.id}>{p.name} — {money(p.price)}</option>)}</select></label><div className="formGrid"><label>Início<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Fim<input type="date" value={end} readOnly/></label><label>Pagamento<select name="method"><option value="pix">Pix</option><option value="card">Cartão</option><option value="cash">Dinheiro</option><option value="transfer">Transferência</option></select></label></div><FormActions onClose={onClose}/></form></Modal>}

function Workouts(){
 const [rows,setRows]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[modal,setModal]=useState(false),[detail,setDetail]=useState<any>(null),[exerciseModal,setExerciseModal]=useState(false);
 const load=()=>Promise.all([api('/api/workouts'),api('/api/students')]).then(([w,s])=>{setRows(w);setStudents(s)});useEffect(()=>{load()},[]);
 return <><Toolbar title="Treinos" subtitle="Fichas e exercícios" button="Novo treino" onClick={()=>setModal(true)}/><section className="card tableCard"><Table headers={['Treino','Aluno','Objetivo','Exercícios','Revisão','Ações']} rows={rows.map(w=><tr key={w.id}><td><b>{w.name}</b></td><td>{w.student_name}</td><td>{w.objective||'—'}</td><td>{w.exercise_count}</td><td>{date(w.review_on)}</td><td><button className="linkBtn" onClick={()=>api('/api/workouts/'+w.id).then(setDetail)}>Abrir ficha</button></td></tr>)}/></section>{modal&&<WorkoutModal students={students} onClose={()=>setModal(false)} onSave={async d=>{await post('/api/workouts',d);setModal(false);load()}}/>}{detail&&<WorkoutDetail data={detail} onClose={()=>setDetail(null)} onAdd={()=>setExerciseModal(true)}/>} {exerciseModal&&detail&&<ExerciseModal workoutId={detail.workout.id} onClose={()=>setExerciseModal(false)} onSave={async d=>{await post('/api/workouts/'+detail.workout.id+'/exercises',d);setExerciseModal(false);api('/api/workouts/'+detail.workout.id).then(setDetail)}}/>}</>
}
function WorkoutModal({students,onClose,onSave}:{students:any[],onClose:()=>void,onSave:(d:any)=>Promise<void>}){return <Modal title="Novo treino" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({student_id:f.get('student_id'),name:f.get('name'),objective:f.get('objective'),starts_on:f.get('starts_on'),review_on:f.get('review_on'),notes:f.get('notes')})}}><div className="formGrid"><label>Aluno<select name="student_id" required><option value="">Selecione</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>Nome do treino<input name="name" required placeholder="Treino A — Hipertrofia"/></label><label>Objetivo<input name="objective"/></label><label>Início<input type="date" name="starts_on"/></label><label>Revisão<input type="date" name="review_on"/></label><label className="fullField">Observações<textarea name="notes"/></label></div><FormActions onClose={onClose}/></form></Modal>}
function WorkoutDetail({data,onClose,onAdd}:{data:any,onClose:()=>void,onAdd:()=>void}){return <Modal title={data.workout.name} onClose={onClose}><div className="detailHeader"><div className="icon red"><Dumbbell/></div><div><b>{data.workout.student_name}</b><span>{data.workout.objective||'Sem objetivo definido'}</span></div><button className="primary smallBtn" onClick={onAdd}><Plus size={15}/>Adicionar exercício</button></div><div className="exerciseList">{data.exercises.map((e:any,i:number)=><div className="exercise" key={e.id}><b>{i+1}. {e.exercise_name}</b><span>{e.sets||'—'} séries · {e.reps||'—'} reps · {e.load||'peso livre'} · {e.rest||'—'} descanso</span></div>)}{!data.exercises.length&&<Empty text="Nenhum exercício adicionado ainda."/>}</div></Modal>}
function ExerciseModal({workoutId,onClose,onSave}:{workoutId:string,onClose:()=>void,onSave:(d:any)=>Promise<void>}){const [exercises,setExercises]=useState<any[]>([]);useEffect(()=>{api('/api/exercises').then(setExercises)},[]);return <Modal title="Adicionar exercício" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({exercise_id:f.get('exercise_id'),position:Number(f.get('position')),sets:f.get('sets'),reps:f.get('reps'),load:f.get('load'),rest:f.get('rest'),notes:f.get('notes')})}}><div className="formGrid"><label className="fullField">Exercício<select name="exercise_id" required>{exercises.map(x=><option key={x.id} value={x.id}>{x.name} · {x.muscle_group}</option>)}</select></label><label>Posição<input type="number" name="position" defaultValue="0" min="0"/></label><label>Séries<input name="sets" placeholder="3"/></label><label>Repetições<input name="reps" placeholder="10-12"/></label><label>Carga<input name="load" placeholder="20 kg"/></label><label>Descanso<input name="rest" placeholder="60s"/></label></div><FormActions onClose={onClose}/></form></Modal>}

function Finance(){const [rows,setRows]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[modal,setModal]=useState(false);const load=()=>Promise.all([api('/api/payments'),api('/api/students')]).then(([p,s])=>{setRows(p);setStudents(s)});useEffect(()=>{load()},[]);const total=rows.filter(p=>p.status==='paid').reduce((a,p)=>a+Number(p.amount),0);return <><Toolbar title="Financeiro" subtitle={`${rows.length} lançamentos`} button="Registrar pagamento" onClick={()=>setModal(true)}/><div className="summaryCards"><Kpi icon={<CircleDollarSign/>} title="Recebido na lista" value={money(total)} note="pagamentos exibidos" tone="green"/><Kpi icon={<Clock/>} title="Pendentes" value={money(rows.filter(p=>p.status==='pending').reduce((a,p)=>a+Number(p.amount),0))} note="a receber" tone="amber"/></div><section className="card tableCard"><Table headers={['Aluno','Valor','Forma','Status','Data']} rows={rows.map(p=><tr key={p.id}><td><b>{p.student_name}</b></td><td>{money(p.amount)}</td><td>{p.method}</td><td><Badge text={p.status} tone={p.status==='paid'?'green':p.status==='pending'?'amber':'gray'}/></td><td>{dateTime(p.paid_at||p.created_at)}</td></tr>)}/></section>{modal&&<PaymentModal students={students} onClose={()=>setModal(false)} onSave={async d=>{await post('/api/payments',d);setModal(false);load()}}/>}</>}
function PaymentModal({students,onClose,onSave}:{students:any[],onClose:()=>void,onSave:(d:any)=>Promise<void>}){return <Modal title="Registrar pagamento" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({student_id:f.get('student_id'),amount:Number(f.get('amount')),method:f.get('method'),status:f.get('status'),notes:f.get('notes')})}}><div className="formGrid"><label>Aluno<select name="student_id" required><option value="">Selecione</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label><label>Valor<input name="amount" type="number" step="0.01" required/></label><label>Forma<select name="method"><option value="pix">Pix</option><option value="card">Cartão</option><option value="cash">Dinheiro</option><option value="transfer">Transferência</option></select></label><label>Status<select name="status"><option value="paid">Pago</option><option value="pending">Pendente</option></select></label><label className="fullField">Observações<textarea name="notes"/></label></div><FormActions onClose={onClose}/></form></Modal>}

function Agenda(){const [rows,setRows]=useState<any[]>([]),[students,setStudents]=useState<any[]>([]),[modal,setModal]=useState(false);const load=()=>Promise.all([api('/api/appointments'),api('/api/students')]).then(([a,s])=>{setRows(a);setStudents(s)});useEffect(()=>{load()},[]);return <><Toolbar title="Agenda" subtitle="Avaliações, aulas e compromissos" button="Novo agendamento" onClick={()=>setModal(true)}/><section className="agendaGrid">{rows.map(a=><div className="card agendaItem" key={a.id}><div className="time">{dateTime(a.starts_at)}</div><div><Badge text={a.type} tone="red"/><h3>{a.title}</h3><span>{a.student_name||'Sem aluno vinculado'}</span></div><button className="iconBtn" onClick={async()=>{await del('/api/appointments/'+a.id);load()}}><X size={16}/></button></div>)}{!rows.length&&<div className="card"><Empty text="Nenhum agendamento cadastrado."/></div>}</section>{modal&&<AppointmentModal students={students} onClose={()=>setModal(false)} onSave={async d=>{await post('/api/appointments',d);setModal(false);load()}}/>}</>}
function AppointmentModal({students,onClose,onSave}:{students:any[],onClose:()=>void,onSave:(d:any)=>Promise<void>}){return <Modal title="Novo agendamento" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({title:f.get('title'),type:f.get('type'),starts_at:f.get('starts_at'),ends_at:f.get('ends_at'),student_id:f.get('student_id')||undefined,notes:f.get('notes')})}}><div className="formGrid"><label>Título<input name="title" required placeholder="Avaliação física"/></label><label>Tipo<select name="type"><option value="assessment">Avaliação</option><option value="personal">Personal</option><option value="class">Aula</option><option value="meeting">Reunião</option><option value="other">Outro</option></select></label><label>Início<input type="datetime-local" name="starts_at" required/></label><label>Fim<input type="datetime-local" name="ends_at" required/></label><label className="fullField">Aluno<select name="student_id"><option value="">Nenhum</option>{students.map(s=><option key={s.id} value={s.id}>{s.full_name}</option>)}</select></label></div><FormActions onClose={onClose}/></form></Modal>}

function Reports(){const [d,setD]=useState<any>(null);useEffect(()=>{api('/api/reports/summary').then(setD)},[]);if(!d)return <Loading/>;return <><div className="welcomeRow"><div><h2>Relatórios</h2><p>Indicadores básicos da operação.</p></div></div><div className="kpis"><Kpi icon={<Users/>} title="Alunos ativos" value={d.students} note="base atual" tone="red"/><Kpi icon={<Plus/>} title="Novas matrículas" value={d.newEnrollments} note="neste mês" tone="green"/><Kpi icon={<X/>} title="Cancelamentos" value={d.cancellations} note="neste mês" tone="amber"/><Kpi icon={<CircleDollarSign/>} title="Faturamento" value={money(d.revenue)} note="neste mês" tone="green"/></div><section className="card"><div className="sectionHead"><div><h3>Recebimentos por forma</h3><span>Distribuição dos pagamentos</span></div></div><div className="reportBars">{d.byMethod.map((x:any)=><div key={x.method}><span>{x.method}</span><div><i style={{width:`${d.revenue?Math.max(5,Number(x.total)/d.revenue*100):0}%`}}/></div><b>{money(x.total)}</b></div>)}</div><div className="pendingReport"><AlertTriangle size={18}/><div><b>Pendente</b><span>{money(d.pending)} em pagamentos pendentes.</span></div></div></section></>}

function SettingsPage({user}:{user:User}){const [gym,setGym]=useState<any>(null),[plans,setPlans]=useState<any[]>([]),[modal,setModal]=useState(false);const load=()=>Promise.all([api('/api/gym'),api('/api/plans')]).then(([g,p])=>{setGym(g);setPlans(p)});useEffect(()=>{load()},[]);if(!gym)return <Loading/>;return <><div className="settingsGrid"><section className="card"><div className="sectionHead"><div><h3>Dados da academia</h3><span>Informações exibidas no sistema</span></div></div><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await put('/api/gym',{name:f.get('name'),cnpj:f.get('cnpj'),phone:f.get('phone'),email:f.get('email')});alert('Dados salvos.')}}><label>Nome<input name="name" defaultValue={gym.name}/></label><label>CNPJ<input name="cnpj" defaultValue={gym.cnpj||''}/></label><label>Telefone<input name="phone" defaultValue={gym.phone||''}/></label><label>E-mail<input name="email" defaultValue={gym.email||''}/></label><button className="primary">Salvar alterações</button></form></section><section className="card"><div className="sectionHead"><div><h3>Planos</h3><span>Planos disponíveis para matrícula</span></div><button className="primary smallBtn" onClick={()=>setModal(true)}><Plus size={15}/>Novo plano</button></div><div className="miniList">{plans.map(p=><div key={p.id}><div><b>{p.name}</b><span>{p.duration_days} dias</span></div><strong>{money(p.price)}</strong></div>)}</div></section></div><section className="card settingsInfo"><h3>Sessão atual</h3><p>{user.email} · {user.role}. O isolamento entre academias é feito no backend por sessão e `gym_id`.</p></section>{modal&&<PlanModal onClose={()=>setModal(false)} onSave={async d=>{await post('/api/plans',d);setModal(false);load()}}/>}</>}
function PlanModal({onClose,onSave}:{onClose:()=>void,onSave:(d:any)=>Promise<void>}){return <Modal title="Novo plano" onClose={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave({name:f.get('name'),price:Number(f.get('price')),duration_days:Number(f.get('duration_days'))})}}><div className="formGrid"><label>Nome<input name="name" required placeholder="Plano Mensal"/></label><label>Preço<input type="number" name="price" step="0.01" required/></label><label>Duração (dias)<input type="number" name="duration_days" defaultValue="30" required/></label></div><FormActions onClose={onClose}/></form></Modal>}

function Toolbar({title,subtitle,button,onClick,search,setSearch}:{title:string,subtitle:string,button:string,onClick:()=>void,search?:string,setSearch?:(v:string)=>void}){return <div className="toolbar"><div><h2>{title}</h2><p>{subtitle}</p></div><div className="toolbarActions">{setSearch&&<div className="search"><Search size={17}/><input placeholder="Buscar aluno..." value={search} onChange={e=>setSearch(e.target.value)}/></div>}<button className="primary" onClick={onClick}><Plus size={17}/>{button}</button></div></div>}
function Table({headers,rows}:{headers:string[],rows:any[]}){return <div className="tableWrap"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length?rows:<tr><td colSpan={headers.length}><Empty text="Nenhum registro encontrado."/></td></tr>}</tbody></table></div>}
function Badge({text,tone}:{text:string,tone:string}){return <span className={'badge '+tone}>{text}</span>}
function Empty({text}:{text:string}){return <div className="empty"><span>{text}</span></div>}
function Loading(){return <div className="loading"><div className="spinner"/><span>Carregando…</span></div>}
function Modal({title,onClose,children}:{title:string,onClose:()=>void,children:any}){return <div className="modalOverlay"><div className="modal"><div className="modalHead"><h2>{title}</h2><button className="iconBtn" onClick={onClose}><X/></button></div>{children}</div></div>}
function FormActions({onClose}:{onClose:()=>void}){return <div className="formActions"><button type="button" className="secondary" onClick={onClose}>Cancelar</button><button type="submit" className="primary">Salvar</button></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
